# Generated by Django 5.1.7 on 2025-05-03 11:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_student_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_out_of_bound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='attachment_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.location'),
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.location')),
            ],
            options={
                'db_table': 'Camera',
            },
        ),
    ]
