# Generated by Django 5.1.7 on 2025-03-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
